### ISSUE TITLE
TypeError: only integer scalar arrays can be converted to a scalar index

### ISSUE THREAD

**Issue by trustablecoder** [FrenkT/LaneTracking#4] opened 2021-04-05 13:08 UTC
I am giving this error when I tried to run main.py
cv2.line(frame, (predicted[0][0], predicted[0][1]), (predicted[0][2], predicted[0][3]), (0, 0, 255), 5)
TypeError: only integer scalar arrays can be converted to a scalar index

How can I fix it?

**Comment by FrenkT** [comment] 2021-04-19 19:35
Hi,

I am not able to reproduce your issue. Could you try running with the environment descirbed in the requirements.txt that I just pushed?

**Comment by stu12140513** [comment] 2022-04-21 01:47
Although this question is over a year old....
try this
cv2.line(frame,(int(predicted[0][0]), int(predicted[0][1])),(int(predicted[0][2]), int(predicted[0][3])),(0, 0, 255), 5)

**Comment by waqarsqureshi** [comment] 2023-01-24 14:42
It works thanks for the hint @stu12140513 @FrenkT you can close this thread. Perhaps it just the use of python latest version or something else but giving an int make it work.

**Closed as completed** 2023-01-25 20:07 UTC
